//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchCoders.WebUI.Helpers.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResearchCoders.WebUI.Helpers.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a university student and are learning C#, you can email me below to get a free code review of your sample application..
        /// </summary>
        public static string AboutFooterParagraph {
            get {
                return ResourceManager.GetString("AboutFooterParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Research Coders?.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, my name is David Jacobo and I have been a programmer for 10 years developing software. Today I dedicate my development with C# and Asp.Net MVC but my beginnings started with Visual Basic 6 and Visual FoxPro 9.0. I have developed applications for windows desktop and web applications, but most recently have dedicated my learning to mobile development..
        /// </summary>
        public static string AboutParagraph1 {
            get {
                return ResourceManager.GetString("AboutParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this website is to give you my knowledge and experience through articles written and case studies found on this site..
        /// </summary>
        public static string AboutParagraph2 {
            get {
                return ResourceManager.GetString("AboutParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can you find on this site?.
        /// </summary>
        public static string AboutWhatCanYouFind1 {
            get {
                return ResourceManager.GetString("AboutWhatCanYouFind1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code samples in C#.nsid.
        /// </summary>
        public static string AboutWhatCanYouFind2 {
            get {
                return ResourceManager.GetString("AboutWhatCanYouFind2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas and things to consider while programming..
        /// </summary>
        public static string AboutWhatCanYouFind3 {
            get {
                return ResourceManager.GetString("AboutWhatCanYouFind3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge from experience and books..
        /// </summary>
        public static string AboutWhatCanYouFind4 {
            get {
                return ResourceManager.GetString("AboutWhatCanYouFind4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended reading material..
        /// </summary>
        public static string AboutWhatCanYouFind5 {
            get {
                return ResourceManager.GetString("AboutWhatCanYouFind5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE.
        /// </summary>
        public static string GlobalMore {
            get {
                return ResourceManager.GetString("GlobalMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ.
        /// </summary>
        public static string GlobalRead {
            get {
                return ResourceManager.GetString("GlobalRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Driven Design.
        /// </summary>
        public static string HomePageHeaderBox1 {
            get {
                return ResourceManager.GetString("HomePageHeaderBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November 2015.
        /// </summary>
        public static string HomePageHeaderBox1Date {
            get {
                return ResourceManager.GetString("HomePageHeaderBox1Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techniques for creating designs step by step while refactoring and keeping code clean..
        /// </summary>
        public static string HomePageHeaderBox1Preview {
            get {
                return ResourceManager.GetString("HomePageHeaderBox1Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Design Principles.
        /// </summary>
        public static string HomePageHeaderBox2 {
            get {
                return ResourceManager.GetString("HomePageHeaderBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string HomePageHeaderBox2Date {
            get {
                return ResourceManager.GetString("HomePageHeaderBox2Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We all must know the definition for SOLID, but how do they fit our day to day scenarios?.
        /// </summary>
        public static string HomePageHeaderBox2Preview {
            get {
                return ResourceManager.GetString("HomePageHeaderBox2Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Cross-Platform.
        /// </summary>
        public static string HomePageHeaderBox3 {
            get {
                return ResourceManager.GetString("HomePageHeaderBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November 2015.
        /// </summary>
        public static string HomePageHeaderBox3Date {
            get {
                return ResourceManager.GetString("HomePageHeaderBox3Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow Cross-Platform! Hands-on development and samples to get started..
        /// </summary>
        public static string HomePageHeaderBox3Preview {
            get {
                return ResourceManager.GetString("HomePageHeaderBox3Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Patterns.
        /// </summary>
        public static string HomePageHeaderBox4 {
            get {
                return ResourceManager.GetString("HomePageHeaderBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string HomePageHeaderBox4Date {
            get {
                return ResourceManager.GetString("HomePageHeaderBox4Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making the complex simple using the C# language..
        /// </summary>
        public static string HomePageHeaderBox4Preview {
            get {
                return ResourceManager.GetString("HomePageHeaderBox4Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftsmanship.
        /// </summary>
        public static string HomePageSliderText1 {
            get {
                return ResourceManager.GetString("HomePageSliderText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you love quality?.
        /// </summary>
        public static string HomePageSliderText2 {
            get {
                return ResourceManager.GetString("HomePageSliderText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK TO TOP.
        /// </summary>
        public static string MainFooterBackToTop {
            get {
                return ResourceManager.GetString("MainFooterBackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Patterns.
        /// </summary>
        public static string MainMenuDesignPatterns {
            get {
                return ResourceManager.GetString("MainMenuDesignPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email me at.
        /// </summary>
        public static string MainMenuEmailMe {
            get {
                return ResourceManager.GetString("MainMenuEmailMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainMenuHome {
            get {
                return ResourceManager.GetString("MainMenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Cross-Platform.
        /// </summary>
        public static string MainMenuMobile {
            get {
                return ResourceManager.GetString("MainMenuMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Design Principles.
        /// </summary>
        public static string MainMenuSolid {
            get {
                return ResourceManager.GetString("MainMenuSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Driven Design.
        /// </summary>
        public static string MainMenuTestDriven {
            get {
                return ResourceManager.GetString("MainMenuTestDriven", resourceCulture);
            }
        }
    }
}
