//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchCoders.WebUI.Helpers.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResearchCoders.WebUI.Helpers.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Driven Design.
        /// </summary>
        public static string HomePageHeaderBox1 {
            get {
                return ResourceManager.GetString("HomePageHeaderBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Design Principles.
        /// </summary>
        public static string HomePageHeaderBox2 {
            get {
                return ResourceManager.GetString("HomePageHeaderBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Cross-Platform.
        /// </summary>
        public static string HomePageHeaderBox3 {
            get {
                return ResourceManager.GetString("HomePageHeaderBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Patterns.
        /// </summary>
        public static string HomePageHeaderBox4 {
            get {
                return ResourceManager.GetString("HomePageHeaderBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftsmanship.
        /// </summary>
        public static string HomePageSliderText1 {
            get {
                return ResourceManager.GetString("HomePageSliderText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you love quality?.
        /// </summary>
        public static string HomePageSliderText2 {
            get {
                return ResourceManager.GetString("HomePageSliderText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Patterns.
        /// </summary>
        public static string MainMenuDesignPatterns {
            get {
                return ResourceManager.GetString("MainMenuDesignPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email me at.
        /// </summary>
        public static string MainMenuEmailMe {
            get {
                return ResourceManager.GetString("MainMenuEmailMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainMenuHome {
            get {
                return ResourceManager.GetString("MainMenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Cross-Platform.
        /// </summary>
        public static string MainMenuMobile {
            get {
                return ResourceManager.GetString("MainMenuMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Design Principles.
        /// </summary>
        public static string MainMenuSolid {
            get {
                return ResourceManager.GetString("MainMenuSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Driven Design.
        /// </summary>
        public static string MainMenuTestDriven {
            get {
                return ResourceManager.GetString("MainMenuTestDriven", resourceCulture);
            }
        }
    }
}
